---
- name: Check to see if janus has been previously installed.
  stat:
    path: "{{ janus_home_dir }}/{{ item.user }}/.vim/janus"
  register: janus_directory
  with_items: "{{ janus_users }}"

# This task (and those that make use of its `janus_current_commit` variable
# should not be needed since the git module's return values should contain
# the latest commit hash in `after`, and the previous one in `before`.
#
# I've never been able to get the git task in this role to return a `before`
# value of anything but `null`, so this task creates a variable that we can
# use to figure out a `changed_when` value for the git task.
- name: Get latest commit id from existing janus install.
  command: "chdir={{ janus_home_dir }}/{{ item.item.user }}/.vim git rev-parse HEAD"
  with_items: "{{ janus_directory.results }}"
  register: janus_current_commit
  when: "{{ item.stat.exists }}"
  changed_when: false

- name: Back up previous vim install files.
  command: "removes={{ janus_home_dir }}/{{ item.0.user }}/{{ item.1 }} creates={{ janus_home_dir }}/{{ item.0.user }}/{{ item.1 }}.old mv {{ janus_home_dir }}/{{ item.0.user }}/{{ item.1 }} {{ janus_home_dir }}/{{ item.0.user }}/{{ item.1 }}.old"
  with_nested:
    - "{{ janus_users }}"
    - "{{ janus_backup_files }}"
  changed_when: false

# We make this task never indicated `changed` since the subsequent `rake` task
# actually runs git commands.
- name: Clone janus repository to each user's home directory.
  git:
    repo: "https://github.com/carlhuda/janus.git"
    dest: "{{ janus_home_dir }}/{{ item.user }}/.vim"
    update: no
  with_items: "{{ janus_users }}"
  become: True
  register: janus_clone
  changed_when: false

- name: Debug janus_clone.
  debug:
    msg: "{{ item.1.stdout }}"
  with_together:
    - "{{ janus_users }}"
    - "{{ janus_current_commit.results }}"

# This command runs further git commands, so we check to see if the latest
# commit has changed here instead of in the git task.
- name: Run `rake` in each user's new .vim directory.
  command: "chdir={{ janus_home_dir }}/{{ item.0.user }}/.vim rake"
  with_together:
    - "{{ janus_users }}"
    - "{{ janus_current_commit.results }}"
  become: True
  register: rake
  when: janus_always_run_rake
  changed_when: "'{{ item.1.stdout }}' is not defined or ('{{ item.1.stdout }}' is defined and janus_clone.after != '{{ item.1.stdout }}')"

- name: Ensure `.janus` directory exists for each user.
  file:
    path: "{{ janus_home_dir }}/{{ item.user }}/.janus"
    state: directory
  with_items: "{{ janus_users }}"

- name: Clone plugin repos to `.janus` directory for each user.
  git:
    repo: "{{ item.1.url }}"
    dest: "{{ janus_home_dir }}/{{ item.0.user }}/.janus/{{ item.1.name }}"
    force: yes
    update: "{{ janus_vim_plugins_update }}"
  with_nested:
    - "{{ janus_users }}"
    - "{{ janus_vim_plugins }}"

- name: Make sure permissions are correct in user's own home directories.
  file:
    path: "{{ janus_home_dir }}/{{ item.0.user }}/{{ item.1 }}"
    owner: "{{ item.0.user }}"
    group: "{{ item.0.group }}"
    recurse: True
  with_nested:
    - "{{ janus_users }}"
    - "{{ janus_created_directories }}"
  become: True
  register: ownership
  changed_when: false
  failed_when: "ownership.owner != '{{ item.0.user }}' or ownership.group != '{{ item.0.group }}'"
