---
- name: Establish home directory.
  set_fact:
    janus_user_home_dir: "{{ (ansible_system == 'Darwin') | ternary('Users', 'home') }}"

- name: Set full path to user home directory.
  set_fact:
    janus_user_home_path: "/{{ janus_user_home_dir }}/{{ janus_user.name }}"

- name: Set Janus install path.
  set_fact:
    janus_install_path: "{{ janus_user_home_path }}/.vim"

- name: Set Janus plugin directory.
  set_fact:
    janus_plugin_install_path: "{{ janus_user_home_path }}/.janus"

- name: Check to see if janus has been previously installed.
  stat:
    path: "{{ janus_install_path }}/janus"
  register: janus_install_directory

- name: Run pre-install tasks.
  include_tasks: "preinstall.yml"
  when: janus_required_packages != []

- name: Run backup tasks.
  include_tasks: "backup.yml"
  vars:
    backup_file: "{{ backup_file_item }}"
  with_items: "{{ janus_backup_files }}"
  loop_control:
    loop_var: backup_file_item
  when: janus_backup_files != []

- name: Install Janus.
  include_tasks: "install.yml"

- name: Install plugins.
  include_tasks: "plugins.yml"
  when: janus_vim_plugins != []
