---
- name: Check to see if janus has been previously installed.
  stat:
    path: "{{ janus_home_dir }}/{{ item.user }}/.vim/janus"
  register: janus_directory
  with_items: "{{ janus_users }}"

  # - name: Debug janus_directory variable.
  #   debug:
  #     var: janus_directory
  # 
  # - name: Debug individual parts of janus_directory variable.
  #   debug:
  #     msg: "{{ janus_home_dir }}/{{ item.item.user }}/.vim/janus exists: {{ item.stat.exists }}"
  #   with_items: "{{ janus_directory.results }}"

- name: Get latest commit id from existing janus install.
  command: "chdir={{ janus_home_dir }}/{{ item.item.user }}/.vim git rev-parse HEAD"
  with_items: "{{ janus_directory.results }}"
  register: janus_current_commit
  when: "{{ item.stat.exists }}"

- name: Debug individual parts of janus_current_commit variable.
  debug:
    msg: "{{ item }}"
    with_items: "{{ janus_current_commit.results }}"

- name: Back up previous vim install files.
  command: "removes={{ janus_home_dir }}/{{ item.0.user }}/{{ item.1 }} creates={{ janus_home_dir }}/{{ item.0.user }}/{{ item.1 }}.old mv {{ janus_home_dir }}/{{ item.0.user }}/{{ item.1 }} {{ janus_home_dir }}/{{ item.0.user }}/{{ item.1 }}.old"
  with_nested:
    - "{{ janus_users }}"
    - "{{ janus_backup_files }}"
  changed_when: false

- name: Clone janus repository to each user's home directory.
  git:
    repo: "https://github.com/carlhuda/janus.git"
    dest: "{{ janus_home_dir }}/{{ item.user }}/.vim"
    update: no
  with_items: "{{ janus_users }}"
  become: True

- name: Ensure `.janus` directory exists for each user.
  file:
    path: "{{ janus_home_dir }}/{{ item.user }}/.janus"
    state: directory
  with_items: "{{ janus_users }}"

- name: Clone plugin repos to `.janus` directory for each user.
  git:
    repo: "{{ item.1.url }}"
    dest: "{{ janus_home_dir }}/{{ item.0.user }}/.janus/{{ item.1.name }}"
    force: yes
    update: "{{ janus_vim_plugins_update }}"
  with_nested:
    - "{{ janus_users }}"
    - "{{ janus_vim_plugins }}"

- name: Run `rake` in each user's new .vim directory.
  command: "chdir={{ janus_home_dir }}/{{ item.user }}/.vim rake"
  with_items: "{{ janus_users }}"
  become: True
  when: janus_always_run_rake

- name: Make sure permissions are correct in user's own home directories.
  file:
    path: "{{ janus_home_dir }}/{{ item.0.user }}/{{ item.1 }}"
    owner: "{{ item.0.user }}"
    group: "{{ item.0.group }}"
    recurse: True
  with_nested:
    - "{{ janus_users }}"
    - "{{ janus_created_directories }}"
  become: True
  register: ownership
  changed_when: false
  failed_when: "ownership.owner != '{{ item.0.user }}' or ownership.group != '{{ item.0.group }}'"
