---
# Plugin install tasks.

- name: Ensure `.janus` directory exists.
  file:
    path: "{{ janus_plugin_install_path }}"
    state: directory
    owner: "{{ janus_user.name }}"
    group: "{{ janus_user.group }}"

- name: Clone plugin repos to `.janus` directory.
  git:
    repo: "{{ plugin.url }}"
    dest: "{{ janus_plugin_install_path }}/{{ plugin.name }}"
    force: "{{ plugin.force | default(false) }}"
    update: "{{ plugin.updaterepo | default(true) }}"
    version: "{{ plugin.version | default('HEAD') }}"
  with_items: "{{ janus_vim_plugins }}"
  loop_control:
    loop_var: plugin

- name: Set file ownership of plugin directory.
  file:
    path: "{{ janus_plugin_install_path }}"
    state: directory
    owner: "{{ janus_user.name }}"
    group: "{{ janus_user.group }}"
    recurse: true
  changed_when: false
