---
# Pre-install tasks.

- name: Ensure required packages are installed.
  block:
    - name: Install packages for Linux.
      package:
        name: "{{ janus_required_packages | default([]) }}"
        state: present
      when: "ansible_system == 'Linux'"

    - name: Install packages for macOS.
      homebrew:
        name: "{{ janus_required_packages | default([]) }}"
        state: present
      when: "ansible_system == 'Darwin'"
