---
# Pre-install tasks.

- name: Ensure required packages are installed.
  block:
    - name: Install packages for Linux.
      package:
        name: "{{ linux_package }}"
        state: present
      with_items: "{{ janus_required_packages }}"
      loop_control:
        loop_var: linux_package
      when: ansible_system == "Linux"

    - name: Install packages for macOS.
      homebrew:
        name: "{{ macos_package }}"
        state: present
      with_items: "{{ janus_required_packages }}"
      loop_control:
        loop_var: macos_package
      when: ansible_system == "Darwin"
